#!/usr/bin/env python

import glob
import json
import re

# Quick and messy little script to pull in a bunch of mcmetas to get their animation info

for fn in sorted(glob.glob("*.mcmeta")):
	with open(fn, 'r') as fh:
		#data = json.load(fh)
		data = fh.read()
		data = data.replace("\n", "")
		data = re.sub(" +", " ", data)
	name = fn.split(".")[0]
	print(f'"{name}": \'{data}\',')
